# Generated by Django 5.2 on 2025-05-05 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_manufacture', models.PositiveIntegerField(verbose_name='Year of Manufacture')),
                ('model', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(max_length=50)),
                ('number_of_doors', models.PositiveIntegerField()),
                ('engine_power', models.FloatField(verbose_name='Engine Power (cc)')),
                ('mileage', models.PositiveIntegerField(verbose_name='Historical Mileage')),
                ('oil_change_frequency', models.CharField(max_length=100)),
                ('filter_change_frequency', models.CharField(max_length=100)),
                ('engine_modifications', models.BooleanField(default=False)),
                ('critical_replacements', models.BooleanField(default=False)),
                ('documentation_in_order', models.BooleanField(default=True)),
                ('taxes_in_order', models.BooleanField(default=True)),
                ('technical_review_valid', models.BooleanField(default=True)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='evaluations/images/')),
                ('left_side_image', models.ImageField(blank=True, null=True, upload_to='evaluations/images/')),
                ('right_side_image', models.ImageField(blank=True, null=True, upload_to='evaluations/images/')),
                ('rear_image', models.ImageField(blank=True, null=True, upload_to='evaluations/images/')),
                ('engine_image', models.ImageField(blank=True, null=True, upload_to='evaluations/images/')),
                ('interior_image', models.ImageField(blank=True, null=True, upload_to='evaluations/images/')),
                ('seats_image', models.ImageField(blank=True, null=True, upload_to='evaluations/images/')),
                ('dashboard_image', models.ImageField(blank=True, null=True, upload_to='evaluations/images/')),
                ('valued_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mae', models.FloatField()),
                ('squared', models.FloatField()),
                ('rmse', models.FloatField()),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('air_conditioning_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_conditioning_condition', to='core.vehiclecondition')),
                ('body_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_condition', to='core.vehiclecondition')),
                ('brakes_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brakes_condition', to='core.vehiclecondition')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiclebrand', verbose_name='Brand')),
                ('chassis_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chassis_condition', to='core.vehiclecondition')),
                ('copied_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_evaluations', to=settings.AUTH_USER_MODEL)),
                ('electrical_system_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_system_condition', to='core.vehiclecondition')),
                ('exhaust_system_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhaust_system_condition', to='core.vehiclecondition')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fueltype', verbose_name='Fuel Type')),
                ('suspension_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspension_condition', to='core.vehiclecondition')),
                ('traction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tractiontype', verbose_name='Traction Type')),
                ('transmission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transmissiontype', verbose_name='Transmission Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('sold', 'Sold')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='publications/images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vehicle_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.vehicleevaluation', verbose_name='Vehicle Evaluation')),
            ],
        ),
    ]
